### ISSUE TITLE
Add command to manage Packages, name, build script in GitDepend.json

### ISSUE THREAD

**Issue by pdubb29** [GitDepend/GitDepend#158] opened 2017-03-03 20:24 UTC
Currently there is no way to update the GitDepend.Json file for these following properties:

* Name
* Packages dir
* Build script

**Comment by kjjuno** [comment] 2017-03-03 20:37
The init verb does some of this. It doesn't currently manage the dependencies though.

**Comment by kjjuno** [comment] 2017-03-03 20:51
This seems to be a duplicate of #148

**Closed** 2017-03-03 20:52 UTC
Labels: wontfix
